version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/warfiles/
hooks:
  BeforeInstall:
    - location: Scripts/Beforeinstall.sh
  AfterInstall:
    - location: Scripts/Afterinstall.sh
      timeout: 180
      runas: ubuntu

